### ISSUE TITLE
Send audio back to the customer ?? 

### ISSUE THREAD

**Issue by jays0606** [deepgram/amazon-connect-integration#4]
So in this workflow, i can receive the user audio stream's transcript to my callback url via deepgram. 

With the transcript, i want to create a ai chat response, and play the response back to the customer. 

Is there a connect flow diagram example which i can reference or follow ?? 

@RyanChimienti 

Thank you very much.

**Comment by RyanChimienti** [comment]
You can ingest information back into Connect using Invoke Lambda Function blocks in the contact flow. For example, you might invoke a lambda function that returns the AI chat response as text, and then follow it with a Say Prompt block that speaks that response.

**Comment by jays0606** [comment]
So basically, this is how i've implemented. 

1. After chat response is received, call lambda function to update contact attributes.
2. lambda sets contact attributes `chat_response={ai_response}, is_chat_updated=true`. 
3. In the connect flow diagram, i have an infinite loop which checks the contact attributes whether `is_chat_updated` is true.
4. if match, play the `chat_response` using Play prompt, and set the `is_chat_updated` to false again. 
5. If not match, play silence (500ms SSML break), and loop back to the infinite loop. 

It works fine, but the this is essentially polling the `check_contact_attributes` to check whether a new chat_response is received every 500ms, which is causing some latency. 

i've reduced the polling interval to 100ms, 300ms, but lower they become, the input audio stream is somehow not processed correctly. i stopped getting proper transcription results. 

is there any alternative architecture? Is it possible that the input stream audio is somehow different, if the looping interval is quite low ??

**Comment by RyanChimienti** [comment]
Interesting, I'm not sure why the shorter polling interval would be messing up the transcripts. I wonder if the short loop is locking up connect and interfering with the audio streaming?

Here's one idea...rather than looping in the contact flow to see whether the bot response is ready, you could try running that loop within a lambda function instead. Something like:

1. Contact flow calls lambda function to see if AI response is ready
2. Lambda function polls an external cache, returning the AI response when it appears
3. If the lambda function times out (I believe Connect will time out invoked lambdas after 8 seconds by default), re-invoke the lambda from the Contact flow
4. Otherwise, if the lambda function returns the AI response, play it

**Comment by jays0606** [comment]
It works !!! 

Thank you very much @RyanChimienti for your assistance. 

I can't thank you more.
